### ISSUE TITLE
Change the drop-menu so that it's initial starting key is C instead of Gb

### ISSUE THREAD

**Issue by Don-Stevenson** [KCarlile/flashchord#30]
## Background
The key selection menu starts with Any (default) and lists the keys as major keys (circle of fifths from Gb to F#), then the minor keys (circle of fifths from Eb to D#). However, it's understandable that the extremes are the least likely keys.

## Acceptance Criteria
- The key selection dropdown list still starts with Any
- The remaining keys are in a reasonable order that makes sense to a user selecting them from the list

## Approach
- Proposal: list the keys in ascending flats and sharps, major, then minor
- List:
  - Any
  - C Major
  - F Major (1 flat)
  - G Major (1 sharp)
  - B♭ Major (2 flats)
  - D Major (2 sharps)
  - E♭ Major (...and so on)
  - A Major
  - A♭ Major
  - E Major
  - D♭ Major
  - B Major
  - G♭ Major
  - F♯ Major
  - A Minor
  - D Minor (1 flat)
  - E Minor (1 sharp)
  - G Minor (2 flats)
  - B Minor (2 sharps)
  - C Minor (...and so on)
  - F♯ Minor
  - F Minor
  - C♯ Minor
  - B♭ Minor
  - G♯ Minor
  - E♭ Minor
  - D♯ Minor

- Alternate proposal: list the keys chromatically (but then where do we start?)

**Comment by Don-Stevenson** [comment]
@KCarlile I think the circle of 5th's ideas is good to follow starting on C. 

The above approach you gave can certainly work.  

My thought would be to have two pull-down menus: one for major and another for minor.

The options array would look something like
                                    
[C#, F#, B, E, A, D, G, C, F, Bb, Eb,Ab,Db,Gb,Cb]

And default to C major (i.e. start in the middle).

Your input is welcome!

**Comment by KCarlile** [comment]
Hmm, are you advocating that the default be C rather than "Any?" I can't default to Any and have the default in the dropdown be C, but if you think we should start on C _rather than_ Any, that's something I could consider.

If we have 2 dropdowns, how would the system know which one to use if one is set to C Major and one is set to D minor?

Maybe I need to think about a totally different UI experience for this.

**Comment by Don-Stevenson** [comment]
_are you advocating that the default be C rather than "Any?"_  Yes, that's what I am advocating. I think the "any" is unnecessary, but it may be a result of a function requirement on the site that I do yet realize.

__If we have 2 dropdowns, how would the system know which one to use if one is set to C Major and one is set to D minor?__ 
This is a great catch!  Maybe it's best handled by a "major or minor" check box and then the circle of 5ths. I'm certainly open to different approaches to solving this.

**Comment by KCarlile** [comment]
Ah, interesting. So a dropdown to select the root of the key and then a radio for the type of key (major/minor). That might work.

As for the "Any" key option, that was the original intent I wanted. I wanted the option to not be restricted to a key. I wanted the be thrown every possible chord on the neck so I would have to learn any chord in any position. (That's the idea anyway.)

So I might be okay having Any not be the default, but I definitely don't want to remove it.

**Comment by Don-Stevenson** [comment]
_So I might be okay having Any not be the default, but I definitely don't want to remove it._

I see your design point for what "any" is now more clearly and agree that it's more useful.  Maybe the words "random key" (if this is what it does) might be more descriptive.

**Comment by Steve-CCity** [comment]
Hi
I saw the reddit post and have am interested in helping out since I just happen to be in the process of learning Git right now and think this webtool/site  is an awesome idea.

I like the direction you are going with this discussion.  The drop down and radio button sounds really good to me. 
I also agree that starting with a specific guitar appropriate key makes sense as the default.  I think the one to use might be A - center of the neck etc.  My second choice would be E, C would be my third choice I think. 
It sounds like Any means Random, if so then I agree that Random is clearer.

I hope this input is helpful.  If I can help out and not slow you down I'd love to do so.
Steve

**Comment by Don-Stevenson** [comment]
@Steve-CCity Thanks for the input.  I am not the lead on this project, @KCarlile is, but for what it's worth, I'd be happy to have you aboard!

While we are all guitarists here, I think the idea for the site was to be multi-instrument friendly.  A and E are not such friendly horn keys for instance. From my perspective, C is one of those keys that most instruments find to be agreeable.

Out of curiosity, what is your preferred tech stack to work in? 

Thanks again!

**Comment by KCarlile** [comment]
Hey @Steve-CCity, welcome! Please send me an email to `info@flashchord.com` so I can invite you to our chat.

**Comment by Steve-CCity** [comment]
Hi Guys
Kenny - I sent you the email  to info@flashchord.com.  Did you get it
As I indicated above I am in the process of learning Git.  Taking a Coursera course since all of my past attempts have been failures.  Doing pretty well this time.  I have some local repos setup and have connected them to either GitHub or BitBucket and have been playing with Cloning, staging, committing, pushing etc.  I also cloned the flashchord project to a local repo and have been able to run it locally.  So I think I am now positioned to be able to help out a bit, if desired.
So, if you want me to work on something, let me know.  Starting off easy please.  But only if it will be helpful.

**Comment by KCarlile** [comment]
Hey @Steve-CCity. That's weird, I didn't get any email from you. I'll test the address again. I just need to get your email address so I can add you to our Slack for casual discussions (so we aren't clogging up issues like this :D ), so you can either post your email address (obfuscated so it doesn't get scraped for spam) or try contacting me through this: http://www.kennycarlile.com/contact

**Comment by KCarlile** [comment]
I just tested the info@flashchord.com email from my work email and it went through fine. I even checked my spam folder, so it's weird that I didn't get your email.

**Comment by Steve-CCity** [comment]
Sent to both the contact form and the email

**Comment by KCarlile** [comment]
This was addressed in PR #41 and is testable at http://dev.flashchord.com/

**Comment by Steve-CCity** [comment]
I see the Ready for testing tag.  Went to http://dev.flashchord.com/ and the first chord was not C

**Comment by KCarlile** [comment]
@Steve-CCity, thanks for testing. It's looking good to me. Just to be clear, it's not that the first chord generated is C but rather that the first _key selected_ is C major. See the screenshot below.
![image](https://user-images.githubusercontent.com/4503624/86068699-e914c000-ba2c-11ea-8330-5d64a94860f5.png)

**Comment by Steve-CCity** [comment]
Caught my mistake.  Just edited my comment.

**Comment by KCarlile** [comment]
It is indeed the Circle of Fifths spreading out from C Major in the middle.

**Comment by KCarlile** [comment]
@Don-Stevenson, this was your ticket, so are you okay with this?

**Comment by Don-Stevenson** [comment]
@KCarlile  Thanks for the note.  Sorry, I have busy the last few days.

I was able to look through the dev mode and it looks great to me!

**Comment by KCarlile** [comment]
Closed in release 1.5.
